### ISSUE TITLE
Compiler warnings with fckit

### ISSUE THREAD

**Issue by rhoneyager** [ecmwf/fckit#10]
When doing a build test of the UFO bundle on Apple Clang, several warnings were noted regarding 1) uninitialized memory use and 2) functions with names that shadow compiler intrinsics.

The log: [fckit-log.txt](https://github.com/ecmwf/fckit/files/3605698/fckit-log.txt)

These should probably be passed upstream, but I am recording these here in case anyone stumbles across fckit-related issues.

**Comment by wdeconinck** [comment]
Thank you @rhoneyager  for this report.  Nothing looks severe but it would be nice to have no warnings of course. Which Fortran compiler / flags did you use? (Apple Clang is for C/C++).

**Comment by rhoneyager** [comment]
Hi. gfortran 9.2 was used for this build, with the ```-Wall``` option.

**Comment by wdeconinck** [comment]
Thank you @rhoneyager I finally got around to dealing with these warnings. Hopefully it fixes all of the warnings -- at least it does all the ones I encountered with gfortran 9.3
