### ISSUE TITLE
NVIDIA SDK replaces PGI

### ISSUE THREAD

**Issue by mmiesch** [ecmwf/fckit#16]
Now that NVIDIA has taken over control of the PGI compiler suite, they are transitioning to a new naming scheme.  For example, `pgfortran` and `gcc` are being replaced with `nvfortran` and `nvc`.  

More to the point, the CMake compiler IDs have changed.  For example, in order to compile fckit using the NVIDIA SDK 21.5 version of the compilers, I had to change this line from `PGI` to `NVHPC`:

https://github.com/ecmwf/fckit/blob/3f612e107682c61c0b6806ea3fc12e9509a90664/src/tests/CMakeLists.txt#L106

Other occurrences of PGI in the CMake code do not seem to need special attention.  Perhaps they have fixed some of the bugs. 

Just something to be aware of.

**Comment by wdeconinck** [comment]
Thanks for discovering this. This seems to be a CMake 3.20 feature or perhaps bug? https://cmake.org/cmake/help/latest/release/3.20.html#compilers
I will do some testing and adapt fckit.

**Comment by mmiesch** [comment]
Yes - perhaps - I was using CMake 3.20

**Comment by wdeconinck** [comment]
@mmiesch , the develop branch is now compatible with CMake 3.20+ 
With CMake 3.18, 3.19 (tested) , nvhpc 21.5 was recognised as PGI still.

**Comment by wdeconinck** [comment]
This issue can be closed now.
