### ISSUE TITLE
Timeout failures for fckit_test_configuration_fails

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/fckit#20]
I am getting transient timeout failures in fckit_test_configuration_fails on some platforms.  Increasing the timeout to, say, 100 seems to work in that the failures go away.  There is a big variation in runtime within those limits though.

Can the timeout be increased for this test?  Or can the timeout be removed altogether?

**Comment by wdeconinck** [comment]
I don't think we can remove the timeout. It was there to prevent continuous integration to timeout at the default 1500 seconds, which must be happening sometimes.
In my experience the 5s was always enough. What is the platform or compiler you're using?
I am OK to increase this number. Perhaps 100 is too long still? What is the maximum variability you encountered?

**Comment by DJDavies2** [comment]
Is the solution in #21 okay?

**Comment by wdeconinck** [comment]
Perfect! Thanks! Merged in develop.
