### ISSUE TITLE
Shared libraries and PGI 18.7

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/fckit#30]
### What happened?

Building fckit with Portland 18.7 results in static libraries; I would like shared libraries.

I tried modifying the check in src/fckit/CMakeLists.txt to 18.7 and shared libraries were build just fine.

### What are the steps to reproduce the bug?

Build fckit with pgfortran 18.7

### Version

head of develop

### Platform (OS and architecture)

Linux

**Comment by wdeconinck** [comment]
Hi @DJDavies2, that was due to a compilation problem. If you managed to get the software stack working with 18.7 as suggested in #31 then that is fine for me. We are not using this old compiler any longer, so I cannot verify myself.
